#!/bin/sh
#
# Starts player server.
#

# Make sure the roomba config file exists
[ -f /root/roomba.cfg ] || exit 0

start() {
 	echo -n "Starting player server:"
	start-stop-daemon --start --quiet --name player --exec /usr/local/bin/player /root/roomba.cfg &
	echo "OK"
}
stop() {
	echo -n "Stopping player server: "
	start-stop-daemon --stop --quiet --name player
	echo "OK"
}
restart() {
	stop
	start
}

case "$1" in
  start)
  	start
	;;
  stop)
  	stop
	;;
  restart|reload)
  	restart
	;;
  *)
	echo $"Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

